version: '3.1'
services:
    zoneminder:
        container_name: zoneminder
        image: ingenium/zoneminder:latest
        restart: unless-stopped
        network: ipcams
        privileged: true
        environment:
            - TZ=America/New_York
            - SHMEM=50%
            - PUID=99
            - PGID=100
            - INSTALL_HOOK=0
            - INSTALL_FACE=0
            - INSTALL_TINY_YOLO=0
            - INSTALL_YOLO=0
            - MULTI_PORT_START=0
            - MULTI_PORT_END=0
        volumes:
            - config:/config:rw
            - data:/var/cache/zoneminder:rw
	devices:
            - "/dev/dri:/dev/dri"
volumes:
    config:
    data:
